name: github pages

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: newam
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check -L --option log-lines 0
      - run: nix build -L --option log-lines 0
      # https://github.com/actions/upload-pages-artifact?tab=readme-ov-file#file-permissions
      - name: fix permissions
        run: |
          cp -rL result public
          chmod 777 -R public
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
